#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 14 22:26:06 2018

@author: peternagy96
"""

import os
import shutil





dir = "/home/peternagy96/Project/server/00_Class_1/FPS_0"
directory= os.listdir("/home/peternagy96/Project/server/00_Class_1/FPS_0")
for file in directory:
    print(file)
    if (int(file) % 2 == 0):
        hhh = dir + "/" + str(file)
        shutil.rmtree(hhh)
    else:
        continue
    
    

